kafka:
  clusters:
    - name: local
      bootstrapServers:  "localhost:9092,localhost:9093,localhost:9094"
      kafkaConnect:
                  - name: first
                    address: http://localhost:8083
